# admean conf
CLOCK_ICON=$'\UF017'
CALENDAR_ICON=$'\UF268'
export TMUX_POWERLINE_THEME="admean"
export TMUX_POWERLINE_SEG_TIME_FORMAT="$CLOCK_ICON %H:%M"
export TMUX_POWERLINE_SEG_DATE_FORMAT="$CALENDAR_ICON %d.%m.%Y"
export TMUX_POWERLINE_SEG_WEATHER_LOCATION="Wroclaw"
export TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER="spotify"
